import { create, themes as storybookThemes } from "storybook/theming";

// Generated by apps/storybook/scripts/sync-storybook-theme.mjs.
// Source: packages/uikit/src/styles/globals.css
const colors = {
  accent: {
    DEFAULT: "#1F1F1F",
    foreground: "#FCFCFC",
  },
  appBorderRadius: 8,
  inputBorderRadius: 8,
  light: {
    background: "#F5F5F5",
    border: "#DEDEDE",
    fieldBackground: "#FFFFFF",
    fieldBorder: "#DEDEDE",
    fieldForeground: "#181818",
    foreground: "#181818",
    muted: "#727272",
  },
  dark: {
    background: "#060606",
    border: "#292929",
    fieldBackground: "#181818",
    fieldBorder: "#292929",
    fieldForeground: "#FCFCFC",
    foreground: "#FCFCFC",
    muted: "#A0A0A0",
  },
};

const fontBase = [
  "ui-sans-serif",
  "system-ui",
  "sans-serif",
  '"Apple Color Emoji"',
  '"Segoe UI Emoji"',
  '"Segoe UI Symbol"',
  '"Noto Color Emoji"',
].join(",");

const fontCode = [
  "ui-monospace",
  "SFMono-Regular",
  "Menlo",
  "Monaco",
  "Consolas",
  '"Liberation Mono"',
  '"Courier New"',
  "monospace",
].join(",");

const lightTheme = create({
  ...storybookThemes.light,
  base: "light",
  brandTitle: `<img src="/logo-dark.svg" style="width: 120px; height: auto;" alt="Namespace"/>`,
  // brandUrl: "https://namespace.ninja",
  brandTarget: "_self",
  // Colors
  colorPrimary: colors.accent.DEFAULT,
  colorSecondary: colors.accent.DEFAULT,
  // UI
  appBg: colors.light.background,
  appContentBg: colors.light.background,
  appPreviewBg: colors.light.background,
  appBorderColor: colors.light.border,
  appBorderRadius: colors.appBorderRadius,
  // Typography
  fontBase,
  fontCode,
  // Text
  textColor: colors.light.foreground,
  textInverseColor: colors.accent.foreground,
  textMutedColor: colors.light.muted,
  // Toolbar
  barBg: colors.light.background,
  barTextColor: colors.light.muted,
  barSelectedColor: colors.accent.DEFAULT,
  barHoverColor: colors.light.foreground,
  // Form colors
  inputBg: colors.light.fieldBackground,
  inputBorder: colors.light.fieldBorder,
  inputTextColor: colors.light.fieldForeground,
  inputBorderRadius: colors.inputBorderRadius,
});

const darkTheme = create({
  ...storybookThemes.dark,
  base: "dark",
  brandTitle: `<img src="/logo-light.svg" style="width: 120px; height: auto;" alt="Namespace"/>`,
  // brandUrl: "https://namespace.ninja",
  brandTarget: "_self",
  // Colors
  colorPrimary: colors.accent.DEFAULT,
  colorSecondary: colors.accent.DEFAULT,
  // UI
  appBg: colors.dark.background,
  appContentBg: colors.dark.background,
  appPreviewBg: colors.dark.background,
  appBorderColor: colors.dark.border,
  appBorderRadius: colors.appBorderRadius,
  // Typography
  fontBase,
  fontCode,
  // Text
  textColor: colors.dark.foreground,
  textInverseColor: colors.accent.foreground,
  textMutedColor: colors.dark.muted,
  // Toolbar
  barBg: colors.dark.background,
  barTextColor: colors.dark.muted,
  barSelectedColor: colors.accent.DEFAULT,
  barHoverColor: colors.dark.foreground,
  // Form colors
  inputBg: colors.dark.fieldBackground,
  inputBorder: colors.dark.fieldBorder,
  inputTextColor: colors.dark.fieldForeground,
  inputBorderRadius: colors.inputBorderRadius,
});

export const themes = {
  dark: darkTheme,
  light: lightTheme,
};
