import { create, themes as storybookThemes } from "storybook/theming";

// This file is generated by apps/storybook/scripts/sync-storybook-theme.mjs.
// Update packages/uikit/src/styles/globals.css, then run pnpm sync-theme.
const colors = {
  zinc: {
    "50": "#FAFAFA",
    "100": "#F4F4F5",
    "200": "#E4E4E7",
    "300": "#D4D4D8",
    "400": "#A1A1AA",
    "500": "#71717A",
    "600": "#52525B",
    "700": "#3F3F46",
    "800": "#27272A",
    "900": "#18181B",
    "950": "#09090B",
  },
  accent: {
    DEFAULT: "#1F1F1F",
    foreground: "#FCFCFC",
  },
  light: {
    accent: "#1F1F1F",
    accentForeground: "#FCFCFC",
    background: "#F5F5F5",
    border: "#DEDEDE",
    fieldBackground: "#FFFFFF",
    fieldBorder: "transparent",
    fieldForeground: "#181818",
    foreground: "#181818",
    muted: "#727272",
    surface: "#FFFFFF",
    surfaceForeground: "#181818",
  },
  dark: {
    accent: "#FAFAFA",
    accentForeground: "#0B0B0B",
    background: "#060606",
    border: "#292929",
    fieldBackground: "#181818",
    fieldBorder: "transparent",
    fieldForeground: "#FCFCFC",
    foreground: "#FCFCFC",
    muted: "#A0A0A0",
    surface: "#181818",
    surfaceForeground: "#FCFCFC",
  },
};

const fontBase = [
  "ui-sans-serif",
  "system-ui",
  "sans-serif",
  '"Apple Color Emoji"',
  '"Segoe UI Emoji"',
  '"Segoe UI Symbol"',
  '"Noto Color Emoji"',
].join(",");

const fontCode = [
  "ui-monospace",
  "SFMono-Regular",
  "Menlo",
  "Monaco",
  "Consolas",
  '"Liberation Mono"',
  '"Courier New"',
  "monospace",
].join(",");

const lightTheme = create({
  ...storybookThemes.light,
  base: "light",
  brandTitle: `<img src="/logo-dark.svg" style="width: 120px; height: auto;" alt="Namespace UI"/>`,
  brandTarget: "_self",
  colorPrimary: colors.accent.DEFAULT,
  colorSecondary: colors.accent.DEFAULT,
  appBg: colors.light.background,
  appContentBg: colors.light.background,
  appPreviewBg: colors.light.background,
  appBorderColor: colors.light.border,
  appBorderRadius: 12,
  fontBase,
  fontCode,
  textColor: colors.light.foreground,
  textInverseColor: colors.accent.foreground,
  textMutedColor: colors.light.muted,
  barBg: colors.light.background,
  barTextColor: colors.light.muted,
  barSelectedColor: colors.accent.DEFAULT,
  barHoverColor: colors.light.foreground,
  inputBg: colors.light.fieldBackground,
  inputBorder: colors.light.fieldBorder,
  inputTextColor: colors.light.fieldForeground,
  inputBorderRadius: 8,
});

const darkTheme = create({
  ...storybookThemes.dark,
  base: "dark",
  brandTitle: `<img src="/logo-light.svg" style="width: 120px; height: auto;" alt="Namespace UI"/>`,
  brandTarget: "_self",
  colorPrimary: colors.accent.DEFAULT,
  colorSecondary: colors.accent.DEFAULT,
  appBg: colors.dark.background,
  appContentBg: colors.dark.background,
  appPreviewBg: colors.dark.background,
  appBorderColor: colors.dark.border,
  appBorderRadius: 12,
  fontBase,
  fontCode,
  textColor: colors.dark.foreground,
  textInverseColor: colors.accent.foreground,
  textMutedColor: colors.dark.muted,
  barBg: colors.dark.background,
  barTextColor: colors.dark.muted,
  barSelectedColor: colors.accent.DEFAULT,
  barHoverColor: colors.dark.foreground,
  inputBg: colors.dark.fieldBackground,
  inputBorder: colors.dark.fieldBorder,
  inputTextColor: colors.dark.fieldForeground,
  inputBorderRadius: 8,
});

export const themes = {
  dark: darkTheme,
  light: lightTheme,
};
