minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@thenamespace/*"
blockExoticSubdeps: true
packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  lefthook: true
catalog:
  "@heroui/react": "3.2.1"
  "@heroui/styles": "3.2.1"
  "oxfmt": "0.56.0"
  "oxlint": "1.71.0"
  "react": "19.2.7"
  "react-dom": "19.2.7"
  "tailwindcss": "4.3.2"
  "@tailwindcss/vite": "4.3.2"
  "@tanstack/react-router": "1.170.17"
  "@tanstack/router-plugin": "1.168.19"
  "@tanstack/router-cli": "1.167.18"
  "@tanstack/react-query": "5.101.2"
  "viem": "2.55.0"
  "wagmi": "^3.7.1"
  "@types/react": "19.2.17"
  "@types/node": "26.1.1"
  "@types/react-dom": "19.2.3"
  "typescript": "6.0.3"
  "tsdown": "0.22.3"
  "turbo": "2.10.3"
