import type { ComponentProps, ReactElement } from "react";

import {
  Add01Icon,
  AddCircleIcon,
  AppleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  Attachment01Icon,
  AtIcon,
  Bookmark01Icon,
  Calendar03Icon,
  Cancel01Icon,
  CancelCircleIcon,
  CheckmarkCircle02Icon,
  CheckmarkSquare02Icon,
  Clock01Icon,
  CloudIcon,
  CodeIcon,
  ComputerIcon,
  Copy01Icon,
  CreditCardIcon,
  Delete02Icon,
  Download01Icon,
  EyeIcon,
  FavouriteIcon,
  File01Icon,
  File02Icon,
  FileCodeIcon,
  FloppyDiskIcon,
  Folder01Icon,
  FolderOpenIcon,
  GitForkIcon,
  GithubIcon,
  Globe02Icon,
  GoogleIcon,
  GridViewIcon,
  HelpCircleIcon,
  Image01Icon,
  InformationCircleIcon,
  LeftToRightListBulletIcon,
  LinkedinIcon,
  LockIcon,
  Mail01Icon,
  MasterCardIcon,
  Menu01Icon,
  Mic01Icon,
  Moon02Icon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  Notification01Icon,
  PaintBoardIcon,
  PaypalIcon,
  PencilEdit01Icon,
  PinIcon,
  PlayIcon,
  Plug01Icon,
  QrCodeIcon,
  QuoteUpIcon,
  RefreshIcon,
  Rocket01Icon,
  Search01Icon,
  Settings01Icon,
  ShoppingBag01Icon,
  SparklesIcon,
  SquareUnlock01Icon,
  StarIcon,
  Sun01Icon,
  TextAlignCenterIcon,
  TextAlignJustifyCenterIcon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextBoldIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  TextUnderlineIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  UnfoldMoreIcon,
  UserGroupIcon,
  UserIcon,
  Video01Icon,
  Wallet01Icon,
  Wrench01Icon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";

const icons: Record<string, IconSvgElement> = {
  "add-circle-linear": AddCircleIcon,
  apple: AppleIcon,
  "brand-apple-filled": AppleIcon,
  "alt-arrow-right-linear": ArrowRight01Icon,
  "arrow-down": ArrowDown01Icon,
  "arrow-down-linear": ArrowDown01Icon,
  "arrow-left": ArrowLeft01Icon,
  "arrow-right": ArrowRight01Icon,
  "arrow-up": ArrowUp01Icon,
  "arrow-up-linear": ArrowUp01Icon,
  "arrow-uturn-ccw-left": RefreshIcon,
  "arrow-uturn-cw-right": RefreshIcon,
  at: AtIcon,
  bars: Menu01Icon,
  bell: Notification01Icon,
  bold: TextBoldIcon,
  bookmark: Bookmark01Icon,
  braces: CodeIcon,
  calendar: Calendar03Icon,
  "caret-right": ArrowRight01Icon,
  check: CheckmarkSquare02Icon,
  "check-circle-bold": CheckmarkCircle02Icon,
  "chevron-down": ArrowDown01Icon,
  "chevron-left": ArrowLeft01Icon,
  "chevron-right": ArrowRight01Icon,
  "chevron-up": ArrowUp01Icon,
  "chevrons-expand-vertical": UnfoldMoreIcon,
  circle: HelpCircleIcon,
  "circle-check": CheckmarkCircle02Icon,
  "circle-check-big": CheckmarkCircle02Icon,
  "circle-dashed": HelpCircleIcon,
  "circle-info": InformationCircleIcon,
  "circle-question": HelpCircleIcon,
  "circle-xmark": CancelCircleIcon,
  "circle-xmark-fill": CancelCircleIcon,
  clock: Clock01Icon,
  cloud: CloudIcon,
  "code-fork": GitForkIcon,
  component: GridViewIcon,
  copy: Copy01Icon,
  download: Download01Icon,
  ellipsis: MoreHorizontalIcon,
  "ellipsis-vertical": MoreVerticalIcon,
  envelope: Mail01Icon,
  eye: EyeIcon,
  "file-code-2": FileCodeIcon,
  "file-text": File02Icon,
  "floppy-disk": FloppyDiskIcon,
  folder: Folder01Icon,
  "folder-open": FolderOpenIcon,
  gear: Settings01Icon,
  "gallery-outline": Image01Icon,
  github: GithubIcon,
  "github-icon": GithubIcon,
  google: GoogleIcon,
  "google-icon": GoogleIcon,
  globe: Globe02Icon,
  "global-linear": Globe02Icon,
  heart: FavouriteIcon,
  "heart-bold": FavouriteIcon,
  "heart-fill": FavouriteIcon,
  italic: TextItalicIcon,
  "letter-linear": Mail01Icon,
  "list-ul": LeftToRightListBulletIcon,
  linkedin: LinkedinIcon,
  "linkedin-icon": LinkedinIcon,
  "logo-apple": AppleIcon,
  lock: LockIcon,
  "lock-open": SquareUnlock01Icon,
  microphone: Mic01Icon,
  mastercard: MasterCardIcon,
  "menu-dots-bold": MoreHorizontalIcon,
  monitor: ComputerIcon,
  moon: Moon02Icon,
  "moon-linear": Moon02Icon,
  paperclip: Attachment01Icon,
  "palette-linear": PaintBoardIcon,
  pencil: PencilEdit01Icon,
  paypal: PaypalIcon,
  "baseline-paypal": PaypalIcon,
  person: UserIcon,
  persons: UserGroupIcon,
  picture: Image01Icon,
  pin: PinIcon,
  play: PlayIcon,
  "planet-earth": Globe02Icon,
  "play-16-solid": PlayIcon,
  "plug-connection": Plug01Icon,
  plus: Add01Icon,
  "qr-code": QrCodeIcon,
  quote: QuoteUpIcon,
  refresh: RefreshIcon,
  rocket: Rocket01Icon,
  search: Search01Icon,
  "settings-linear": Settings01Icon,
  "shopping-bag": ShoppingBag01Icon,
  sparkles: SparklesIcon,
  star: StarIcon,
  "star-fill": StarIcon,
  strikethrough: TextStrikethroughIcon,
  sun: Sun01Icon,
  "text-align-center": TextAlignCenterIcon,
  "text-align-justify": TextAlignJustifyCenterIcon,
  "text-align-left": TextAlignLeftIcon,
  "text-align-right": TextAlignRightIcon,
  "thumbs-down": ThumbsDownIcon,
  "thumbs-up": ThumbsUpIcon,
  "trash-2": Delete02Icon,
  "trash-bin": Delete02Icon,
  "trash-bin-trash-linear": Delete02Icon,
  underline: TextUnderlineIcon,
  user: UserIcon,
  "users-group-rounded-linear": UserGroupIcon,
  video: Video01Icon,
  wallet: Wallet01Icon,
  visa: CreditCardIcon,
  "visa-logo-solid": CreditCardIcon,
  wrench: Wrench01Icon,
  x: Cancel01Icon,
};

export interface IconProps extends Omit<
  ComponentProps<typeof HugeiconsIcon>,
  "icon" | "size"
> {
  height?: number | string;
  icon: string;
  inline?: boolean;
  width?: number | string;
}

export function Icon({
  height,
  icon,
  inline: _inline,
  width,
  ...props
}: IconProps): ReactElement {
  const name = icon.includes(":") ? icon.slice(icon.indexOf(":") + 1) : icon;
  const selected = icons[name] ?? File01Icon;
  const dimension = Number(width ?? height ?? 16);
  return (
    <HugeiconsIcon
      aria-hidden={props["aria-label"] ? undefined : true}
      icon={selected}
      size={Number.isFinite(dimension) ? dimension : 16}
      strokeWidth={2}
      {...props}
    />
  );
}
