import type {
  NameProfileEditorCategory,
  NameProfileEditorRecordDefinition,
} from "#/components/name-profile-editor/editor/types";

export const nameProfileEditorCategories: readonly {
  id: NameProfileEditorCategory;
  label: string;
}[] = [
  { id: "general", label: "General" },
  { id: "social", label: "Social" },
  { id: "addresses", label: "Addresses" },
  { id: "website", label: "Website" },
];

export const nameProfileEditorCatalog: readonly NameProfileEditorRecordDefinition[] =
  [
    {
      category: "general",
      description: "The name shown on your public profile.",
      icon: "user",
      id: "text:name",
      key: "name",
      kind: "text",
      label: "Nickname",
      placeholder: "e.g. John",
    },
    {
      category: "general",
      description: "A short introduction shown with your profile.",
      icon: "phone",
      id: "text:description",
      key: "description",
      kind: "text",
      label: "Short bio",
      placeholder: "Tell people about yourself",
    },
    {
      category: "general",
      description: "A conventional web URL associated with the name.",
      icon: "globe",
      id: "text:url",
      key: "url",
      kind: "text",
      label: "Website",
      placeholder: "https://example.com",
    },
    {
      category: "general",
      description: "A public location for the profile.",
      icon: "location",
      id: "text:location",
      key: "location",
      kind: "text",
      label: "Location",
      placeholder: "London, UK",
    },
    {
      category: "general",
      description: "A public contact email.",
      icon: "mail",
      id: "text:email",
      key: "email",
      kind: "text",
      label: "E-Mail",
      placeholder: "hello@example.com",
    },
    {
      category: "social",
      description: "Your X username, without the @ prefix.",
      icon: "x",
      id: "text:com.twitter",
      key: "com.twitter",
      kind: "text",
      label: "Twitter",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your GitHub username.",
      icon: "github",
      id: "text:com.github",
      key: "com.github",
      kind: "text",
      label: "Github",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your Discord username.",
      icon: "discord",
      id: "text:com.discord",
      key: "com.discord",
      kind: "text",
      label: "Discord",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your Telegram username, without the @ prefix.",
      icon: "telegram",
      id: "text:org.telegram",
      key: "org.telegram",
      kind: "text",
      label: "Telegram",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your YouTube channel or handle.",
      icon: "youtube",
      id: "text:com.youtube",
      key: "com.youtube",
      kind: "text",
      label: "YouTube",
      placeholder: "@channel",
    },
    {
      category: "addresses",
      coinType: "60",
      description: "Ethereum and EVM-compatible receiving address.",
      icon: "eth",
      id: "address:60",
      kind: "address",
      label: "Ethereum",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "0",
      description: "Bitcoin receiving address.",
      icon: "btc",
      id: "address:0",
      kind: "address",
      label: "Bitcoin",
      placeholder: "bc1…",
    },
    {
      category: "addresses",
      coinType: "501",
      description: "Solana receiving address.",
      icon: "sol",
      id: "address:501",
      kind: "address",
      label: "Solana",
      placeholder: "Solana address",
    },
    {
      category: "addresses",
      coinType: "2147492101",
      description: "Base receiving address.",
      icon: "base",
      id: "address:2147492101",
      kind: "address",
      label: "Base",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147525809",
      description: "Arbitrum receiving address.",
      icon: "arb",
      id: "address:2147525809",
      kind: "address",
      label: "Arbitrum",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147525868",
      description: "Celo receiving address.",
      icon: "celo",
      id: "address:2147525868",
      kind: "address",
      label: "Celo",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147483785",
      description: "Polygon receiving address.",
      icon: "polygon",
      id: "address:2147483785",
      kind: "address",
      label: "Polygon",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147483658",
      description: "Optimism receiving address.",
      icon: "op",
      id: "address:2147483658",
      kind: "address",
      label: "Optimism",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2155261425",
      description: "Zora receiving address.",
      icon: "zora",
      id: "address:2155261425",
      kind: "address",
      label: "Zora",
      placeholder: "0x0000…",
    },
    {
      category: "website",
      contenthashCodec: "ipfs",
      description: "Content hosted on the InterPlanetary File System.",
      icon: "ipfs",
      id: "contenthash:ipfs",
      kind: "contenthash",
      label: "IPFS",
      placeholder: "ipfs://",
    },
    {
      category: "website",
      contenthashCodec: "onion",
      description: "A Tor onion service address.",
      icon: "onion",
      id: "contenthash:onion",
      kind: "contenthash",
      label: "ONION",
      placeholder: "onion://",
    },
    {
      category: "website",
      contenthashCodec: "arweave",
      description: "Permanently hosted Arweave content.",
      icon: "arweave",
      id: "contenthash:arweave",
      kind: "contenthash",
      label: "ARWEAVE",
      placeholder: "arweave://",
    },
    {
      category: "website",
      contenthashCodec: "skynet",
      description: "Content hosted through the Skynet protocol.",
      icon: "skynet",
      id: "contenthash:skynet",
      kind: "contenthash",
      label: "SKYNET",
      placeholder: "skynet://",
    },
    {
      category: "general",
      description: "The resolver name record.",
      hidden: true,
      icon: "at",
      id: "name",
      kind: "name",
      label: "Name record",
      placeholder: "name.eth",
    },
    {
      category: "general",
      description: "A SECP256k1 public key.",
      hidden: true,
      icon: "key",
      id: "pubkey",
      kind: "pubkey",
      label: "Public key",
      placeholder: "0x…",
    },
    {
      category: "general",
      description: "Add an arbitrary ENS text record.",
      icon: "question",
      id: "custom-text",
      kind: "text",
      label: "Custom",
      placeholder: "Record value",
    },
    {
      category: "general",
      description: "Add arbitrary keyed bytes.",
      hidden: true,
      icon: "database",
      id: "data",
      kind: "data",
      label: "Data",
      placeholder: "0x…",
    },
    {
      category: "general",
      description: "Add ABI data for an ENSIP-4 content type.",
      hidden: true,
      icon: "code",
      id: "abi",
      kind: "abi",
      label: "ABI",
      placeholder: "0x…",
    },
    {
      category: "general",
      description: "Set an EIP-165 interface implementer.",
      hidden: true,
      icon: "interface",
      id: "interface",
      kind: "interface",
      label: "Interface",
      placeholder: "0x0000…",
    },
  ];
