import type {
  NameProfileEditorCategory,
  NameProfileEditorRecordDefinition,
} from "#/components/name-profile-editor/editor/types";

export const nameProfileEditorCategories: readonly {
  id: NameProfileEditorCategory;
  label: string;
}[] = [
  { id: "general", label: "General" },
  { id: "social", label: "Social" },
  { id: "addresses", label: "Addresses" },
  { id: "website", label: "Website" },
  { id: "advanced", label: "Advanced" },
];

export const nameProfileEditorCatalog: readonly NameProfileEditorRecordDefinition[] =
  [
    {
      category: "general",
      description: "The name shown on your public profile.",
      icon: "user",
      id: "text:name",
      key: "name",
      kind: "text",
      label: "Display name",
      placeholder: "Vitalik Buterin",
    },
    {
      category: "general",
      description: "A short introduction shown with your profile.",
      icon: "text",
      id: "text:description",
      key: "description",
      kind: "text",
      label: "Short bio",
      placeholder: "Tell people about yourself",
    },
    {
      category: "general",
      description: "A conventional web URL associated with the name.",
      icon: "globe",
      id: "text:url",
      key: "url",
      kind: "text",
      label: "Website",
      placeholder: "https://example.com",
    },
    {
      category: "general",
      description: "A public location for the profile.",
      icon: "location",
      id: "text:location",
      key: "location",
      kind: "text",
      label: "Location",
      placeholder: "London, UK",
    },
    {
      category: "general",
      description: "A public contact email.",
      icon: "mail",
      id: "text:email",
      key: "email",
      kind: "text",
      label: "Email",
      placeholder: "hello@example.com",
    },
    {
      category: "social",
      description: "Your X username, without the @ prefix.",
      icon: "x",
      id: "text:com.twitter",
      key: "com.twitter",
      kind: "text",
      label: "X",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your GitHub username.",
      icon: "github",
      id: "text:com.github",
      key: "com.github",
      kind: "text",
      label: "GitHub",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your Discord username.",
      icon: "discord",
      id: "text:com.discord",
      key: "com.discord",
      kind: "text",
      label: "Discord",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your Telegram username, without the @ prefix.",
      icon: "telegram",
      id: "text:org.telegram",
      key: "org.telegram",
      kind: "text",
      label: "Telegram",
      placeholder: "username",
    },
    {
      category: "social",
      description: "Your YouTube channel or handle.",
      icon: "youtube",
      id: "text:com.youtube",
      key: "com.youtube",
      kind: "text",
      label: "YouTube",
      placeholder: "@channel",
    },
    {
      category: "addresses",
      coinType: "60",
      description: "Ethereum and EVM-compatible receiving address.",
      icon: "eth",
      id: "address:60",
      kind: "address",
      label: "Ethereum",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "0",
      description: "Bitcoin receiving address.",
      icon: "btc",
      id: "address:0",
      kind: "address",
      label: "Bitcoin",
      placeholder: "bc1…",
    },
    {
      category: "addresses",
      coinType: "501",
      description: "Solana receiving address.",
      icon: "sol",
      id: "address:501",
      kind: "address",
      label: "Solana",
      placeholder: "Solana address",
    },
    {
      category: "addresses",
      coinType: "2147492101",
      description: "Base receiving address.",
      icon: "base",
      id: "address:2147492101",
      kind: "address",
      label: "Base",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147525809",
      description: "Arbitrum receiving address.",
      icon: "arb",
      id: "address:2147525809",
      kind: "address",
      label: "Arbitrum",
      placeholder: "0x0000…",
    },
    {
      category: "addresses",
      coinType: "2147483658",
      description: "Optimism receiving address.",
      icon: "op",
      id: "address:2147483658",
      kind: "address",
      label: "Optimism",
      placeholder: "0x0000…",
    },
    {
      category: "website",
      description: "Decentralized website content hosted on IPFS or IPNS.",
      icon: "link",
      id: "contenthash",
      kind: "contenthash",
      label: "Content hash",
      placeholder: "ipfs://… or ipns://…",
    },
    {
      category: "advanced",
      description: "The resolver name record.",
      icon: "at",
      id: "name",
      kind: "name",
      label: "Name record",
      placeholder: "name.eth",
    },
    {
      category: "advanced",
      description: "A SECP256k1 public key.",
      icon: "key",
      id: "pubkey",
      kind: "pubkey",
      label: "Public key",
      placeholder: "0x…",
    },
    {
      category: "advanced",
      description: "Add an arbitrary ENS text record.",
      icon: "text",
      id: "custom-text",
      kind: "text",
      label: "Custom text",
      placeholder: "Record value",
    },
    {
      category: "advanced",
      description: "Add arbitrary keyed bytes.",
      icon: "database",
      id: "data",
      kind: "data",
      label: "Data",
      placeholder: "0x…",
    },
    {
      category: "advanced",
      description: "Add ABI data for an ENSIP-4 content type.",
      icon: "code",
      id: "abi",
      kind: "abi",
      label: "ABI",
      placeholder: "0x…",
    },
    {
      category: "advanced",
      description: "Set an EIP-165 interface implementer.",
      icon: "interface",
      id: "interface",
      kind: "interface",
      label: "Interface",
      placeholder: "0x0000…",
    },
  ];
